#  image:
#    repository: virtru/tdf-keycloak
#    tag: "6459f0baabe470fccef0f69aa66a1f48036bac61"
##  https://artifacthub.io/packages/helm/bitnami/keycloak
auth:
  createAdminUser: true
  adminUser: keycloakadmin
  adminPassword: mykeycloakpassword
#  postgresql:
#    enabled: false
#    postgresqlUsername: postgres
#    postgresqlPassword: mydbapassword
#    postgresqlDatabase: keycloak_database
#  externalDatabase:
#    host: opentdf-postgresql
#    user: postgres
#    password: postgres
#    database: keycloak_database
extraEnvVars:
#  - name: KEYCLOAK_LOG_LEVEL
#    value: DEBUG
  - name: KEYCLOAK_USER
    value: keycloakadmin
  - name: KEYCLOAK_PASSWORD
    value: mykeycloakpassword
  - name: CLAIMS_URL
    value: http://opentdf-claims:4010/v1/claims_object
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://keycloak.opentdf.us/auth -Dkeycloak.adminUrl=https://keycloak.opentdf.us/auth"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hostname: keycloak.opentdf.us
