global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: mydbapassword

attributes:
  rootPath: /attributes
  publicName: "Attributes"
  logLevel: DEBUG
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_attribute_manager
    password: bXlQb3N0Z3Jlc1Bhc3N3b3Jk
    database: tdf_database
    schema: tdf_attribute
  oidc:
    clientId: tdf-attributes
    clientSecret: myclientsecret
    realm: tdf
    #    trailing / is required
    serverUrl: http://opentdf-keycloak/auth/
    configurationUrl: http://opentdf-keycloak/auth/realms/tdf/.well-known/openid-configuration
    authorizationUrl: https://opentdf.us/keycloak/auth/realms/tdf/protocol/openid-connect/auth
    tokenUrl: https://opentdf.us/keycloak/auth/realms/tdf/protocol/openid-connect/token
  ingress:
    enabled: true
    hosts:
      - host: opentdf.us
        paths:
          - path: /attributes(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
